/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/fky3_room.glb --transform --simplify 
Files: public/models/fky3_room.glb [38.81MB] > E:\Thesis\homepage\home_page\fky3_room-transformed.glb [2.6MB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/fky3_room-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ob_pipe_03.geometry} material={materials.M_mainpipe} />
      <mesh geometry={nodes.pCube1.geometry} material={materials.M_middlelight} />
      <mesh geometry={nodes.ob_book_19.geometry} material={materials.M_bookcase} />
      <mesh geometry={nodes.pCube38.geometry} material={materials.M_TVmap} />
      <mesh geometry={nodes.pPlane4.geometry} material={materials.M_onlycloth} />
      <mesh geometry={nodes.pCube35.geometry} material={materials.M_scifidoor} />
      <mesh geometry={nodes.pCylinder6.geometry} material={materials.M_maintable} />
      <mesh geometry={nodes.pCylinder16.geometry} material={materials.M_lamp} />
      <mesh geometry={nodes.pCube29.geometry} material={materials.M_cubboard} />
      <mesh geometry={nodes.pCube48.geometry} material={materials.M_sofas} />
      <mesh geometry={nodes.polySurface7.geometry} material={materials.M_bed} />
      <mesh geometry={nodes.ob_table_big.geometry} material={materials.M_bigtable} />
      <mesh geometry={nodes.pCube53.geometry} material={materials.aiStandardSurface2} />
      <mesh geometry={nodes.ob_glassfire.geometry} material={materials.aiStandardSurface2} />
      <mesh geometry={nodes.ob_carpet.geometry} material={materials.M_glasscarpet} />
      <mesh geometry={nodes.ob_longsofa.geometry} material={materials.M_sofa_chair} />
      <mesh geometry={nodes.ob_fireplace.geometry} material={materials.M_fireplace} />
      <mesh geometry={nodes.floor.geometry} material={materials.M_floor} />
      <mesh geometry={nodes.wall.geometry} material={materials.M_wall} />
      <mesh geometry={nodes.celing1.geometry} material={materials.M_roof} />
    </group>
  )
}

useGLTF.preload('/fky3_room-transformed.glb')
